name: Jest Tests
on: push
jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        problem-folder:
          # - "problem-01-wena04/problem-a"
          # - "problem-02-wena04/problem-a"
          # - "problem-02-wena04/problem-b"
          # - "problem-03-wena04/problem-a"
          # - "problem-03-wena04/problem-b"
          # - "problem-03-wena04/problem-c"
          # - "problem-04-wena04/problem-a"
          # - "problem-04-wena04/problem-b"
          # - "problem-05-wena04/problem-a"
          # - "problem-05-wena04/problem-b"
          # - "problem-05-wena04/problem-c"
          # - "problem-06-wena04/problem-a"
          # - "problem-06-wena04/problem-b"
          # - "problem-06-wena04/problem-c"
          - "problem-07-wena04/problem-a"
          # - "problem-07-wena04/problem-b"
          # - "problem-07-wena04/problem-c"
          # - "problem-08-wena04/problem-a"
          # - "problem-09-wena04/problem-a"

    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js 22.x
        uses: actions/setup-node@v4
        with:
          node-version: 22.x
      - run: npm install jest
        working-directory: ./INFO-340 Spring 2024/${{ matrix.problem-folder }}
      - run: npm install
        working-directory: ./INFO-340 Spring 2024/${{ matrix.problem-folder }}
      # - run: npm run build --if-present
      - run: npm test
        working-directory: ./INFO-340 Spring 2024/${{ matrix.problem-folder }}
        env:
          CI: true
